### ISSUE TITLE
Consolidate property setting in one location

### ISSUE THREAD

**Issue by spaceisfun** [microsoft/FactoryOrchestrator#21]
Currently, LoadOEMCustomizations() and the FOService ctor both handle setting key properties, fields. This should be done in one location for consistency.

**Comment by byusti** [comment]
Hi! I'm interested in tackling this issue if thats alright

**Comment by spaceisfun** [comment]
@byusti that sounds great, we welcome any and all contributions!

https://github.com/microsoft/FactoryOrchestrator#contributing
Make sure you review the steps here, especially sections 2 and 4 that relate to setup and debugging. Sadly the code is currently not very debugger friendly on Windows Desktop systems due to the noise from the exceptions mentioned in section 4 (#22). I'm hoping to fix that shortly. We are also working on greatly expanding the documentation for this project in the coming weeks.

You can @ me on GitHub if you need help with this issue.

**Comment by byusti** [comment]
@spaceisfun I am moving oem customization checks into the constructor for FOservice, but there is an instance in the code where LoadOEMCustomizations() is called. Should this be replaced with a call to the constructor?

**Comment by byusti** [comment]
The call to LoadOEMCustomizations() occurs in ExecuteServerBootTasks()

**Comment by spaceisfun** [comment]
@byusti 
The reason i filed this issue is my concern with a properties like DisableFileTransferPage, which are set in the ctor() then also set in LoadOEMCustomizations(). The code is hard to read, and understand for example if 

`  try
            {
                DisableFileTransferPage = Convert.ToBoolean(GetValueFromRegistry(_disableFileTransferValue, false), CultureInfo.InvariantCulture);
            }
            catch (Exception)
            { }`

this throws an exception, what value is used (A: the ctor() value) ? if the value is unset in registry, what value is used (A: false, since the second param in GetValueFromRegistry is the value returned if the reg value doesnt exist)... etc?

This is designed to be run as a system service using https://github.com/PeterKottas/DotNetCore.WindowsService. Nothing should call the FOService ctor() other than the system service init code in Main(). 

I would actually suggest the opposite of what you are planning. Move as much as possible out of the ctor() and into one place in the Start()->ExecuteServerBootTasks()->LoadOEMCustomizations() flow; maybe the start of ExecuteServerBootTasks()? If you look at Main() and the WindowsService github i linked above, you will see that serviceConfig.OnStart() is called when the service is started by Windows; OnStart() is essentially my [ServiceMain](https://docs.microsoft.com/en-us/windows/win32/services/service-servicemain-function). That should be where all service init is done imo, the FOService ctor() should do the bare minimum, as that is created before the service is officially "starting" in OnStart().

I think the ctor() could be

```
     lock (_constructorLock)
            {
                if (_singleton != null)
                {
                    throw new FactoryOrchestratorException(Resources.ServiceAlreadyCreatedError);
                }

                ServiceLogger = logger;
                _singleton = this;
           }
```

with the rest done elsewhere as part of Start().

Make sense?

**Comment by byusti** [comment]
@spaceisfun 
Yes, this clarifies a ton. I was confused about what the constructor was being used for.

**Comment by byusti** [comment]
@spaceisfun 
So would it make sense to replace code similar to:
```
 try
 {
                DisableFileTransferPage = Convert.ToBoolean(GetValueFromRegistry(_disableFileTransferValue, false), CultureInfo.InvariantCulture);
 }
 catch (Exception)
 { }
```
with something easier to read like:
```
 try
 {
                DisableFileTransferPage = Convert.ToBoolean(GetValueFromRegistry(_disableFileTransferValue), CultureInfo.InvariantCulture);
 }
 catch (Exception)
 {
       DisableFileTransferPage = false;
 }
```

**Comment by spaceisfun** [comment]
Yeah i think that would help a lot :)

**Comment by byusti** [comment]
@spaceisfun 
rightnow I am throwing an exception as follows:
```
try
{
        DisableFileTransferPage = Convert.ToBoolean(GetValueFromRegistry(_disableFileTransferValue) ?? throw new ArgumentNullException("GetValueFromRegistry(_disableFileTransferValue)"), CultureInfo.InvariantCulture);
}
catch (Exception)
{
       DisableFileTransferPage = false;
}
```

although I am not sure about the message I am using in ArgumentNullException() or if this is the correct exception to begin with.

**Comment by spaceisfun** [comment]
What you did above looks like it will work well :)
