### ISSUE TITLE
FOService should not throw exceptions if registry keys/values are not found

### ISSUE THREAD

**Issue by spaceisfun** [microsoft/FactoryOrchestrator#22]
FOService::GetOEMVersionString()

**Comment by spaceisfun** [comment]
FOService::VerifyContainerConnection()

**Comment by byusti** [comment]
@spaceisfun would this just be a matter of removing the throw statements from each function involving container connections? I think this would also include OService::UpdateContainerId()

**Comment by spaceisfun** [comment]
Pretty much. I actually was able to get a PR out earlier today which will fix this issue, see #29 .

Until that PR is integrated into main (ETA, end of day tomorrow), you can also disable the container checking and the exceptions they throw by setting the following in your registry from an administrator command prompt:
reg add HKLM\System\CurrentControlSet\Control\FactoryOrchestrator /v DisableContainerSupport /t REG_DWORD /d 0x1 /f

See https://github.com/microsoft/FactoryOrchestrator/blob/main/src/Service/ServiceExe.cs, search for _disableContainerValue. The logic that would check for the container and throw exceptions is disabled if this is set.
